#!/usr/bin/env python3
"""
Simple script to generate a health report for testing persistence.
This bypasses the complex agent workflow and directly creates a report.
"""

import json
from health_guardian_agent.database import db
from health_guardian_agent.tools import save_health_report_to_file

def generate_health_report(patient_id: str) -> str:
    """Generate a comprehensive health report for a patient."""

    # Get patient data from database
    health_data = db.get_patient_data(patient_id)

    if not health_data:
        return f"No health data found for patient {patient_id}"

    # Create a comprehensive report
    report = f"""# Health Report for Patient {patient_id}

## Patient Information
- **Patient ID**: {patient_id}
- **Report Date**: {__import__('datetime').datetime.now().strftime('%Y-%m-%d')}

## Current Health Status

### Vital Signs
- **Blood Pressure**: {health_data.get('vital_signs', {}).get('blood_pressure', 'N/A')}
- **Heart Rate**: {health_data.get('vital_signs', {}).get('heart_rate', 'N/A')} bpm
- **Temperature**: {health_data.get('vital_signs', {}).get('temperature', 'N/A')}°F
- **Oxygen Saturation**: {health_data.get('vital_signs', {}).get('oxygen_saturation', 'N/A')}%

### Laboratory Results
- **Glucose**: {health_data.get('lab_results', {}).get('glucose', 'N/A')} mg/dL
- **Cholesterol**: {health_data.get('lab_results', {}).get('cholesterol', 'N/A')} mg/dL
- **Hemoglobin**: {health_data.get('lab_results', {}).get('hemoglobin', 'N/A')} g/dL

### Medications
{chr(10).join(f"- {med}" for med in health_data.get('medications', []))}

### Medical Conditions
{chr(10).join(f"- {condition}" for condition in health_data.get('conditions', []))}

## Health Assessment

### Current Status
The patient's vital signs and laboratory results indicate well-controlled chronic conditions. Regular monitoring and adherence to the prescribed treatment plan are essential for maintaining optimal health.

### Recommendations
1. Continue regular monitoring of blood pressure and blood glucose levels
2. Maintain current medication regimen as prescribed
3. Schedule regular follow-up appointments with healthcare providers
4. Monitor for any changes in symptoms or health status

## Important Notes
- This report is for informational purposes only
- Always consult with qualified healthcare professionals for medical advice
- Report generated from stored patient data

---
*Generated by HealthGuardian Agent*
"""

    return report

def main():
    """Generate and save health report for PAT001."""
    patient_id = "PAT001"
    report_content = generate_health_report(patient_id)

    filename = f"health_report_{patient_id}.md"
    result = save_health_report_to_file(report_content, filename)

    print(f"Health report generated and saved as: {filename}")
    print("Report content preview:")
    print("=" * 50)
    print(report_content[:500] + "..." if len(report_content) > 500 else report_content)

if __name__ == "__main__":
    main()